# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.8,<=3.10  # CPLEX requires python<=3.10
- pip

- atlite>=0.2.9
- pypsa==0.25.2
- linopy
- dask

  # Dependencies of the workflow itself
- xlrd
- openpyxl!=3.1.1
- pycountry
- seaborn
- snakemake-minimal>=7.7.0
- memory_profiler
- yaml
- pytables
- lxml
- powerplantmatching>=0.5.5
- numpy
- pandas>=2.0
- geopandas>=0.11.0
- xarray
- rioxarray
- netcdf4
- networkx
- scipy
- shapely>=2.0
- pyomo
- matplotlib
- proj
- fiona
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- pypsa

  # Keep in conda environment when calling ipython
- ipython

  # From Adrian's wishlist
- ipykernel

  # GIS dependencies:
- cartopy
- descartes
- rasterio!=1.2.10


- pip:
  - tsam>=2.3.1
  - gamspy
